// Build the committed Action bundle (docs/WORKSPACE-DESIGN.md §5.8). An Action runs from its checked-out files with no
// `npm install`, so dist/ holds everything:
//   dist/index.js        the Action: src/index.ts + the engine + typescript + fast-check, one ESM file
//   dist/worker.mjs      the gate worker entry (packages/engine/src/node/worker.mjs, copied verbatim)
//   dist/harness.js      the in-realm gate harness (the engine's sandbox/vmHarness.ts as one IIFE)
//   dist/package.json    {"type":"module"}, so index.js loads as ESM wherever the action is checked out
//   dist/THIRD-PARTY-LICENSES.txt  the licenses of the bundled packages
// The TypeScript lib .d.ts files the compile gate needs are embedded in index.js (src/embedded.ts is replaced).
// Reproducible: same inputs (package-lock.json) → byte-identical dist/; CI checks it with `npm run check:action-dist`.
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { rolldown } from 'rolldown';

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), '..');
process.chdir(pkgDir); // rolldown's region comments are relative to the working directory: keep them stable
// `--out <dir>` builds elsewhere (scripts/check-dist.mjs compares that build with the committed dist/)
const outArg = process.argv.indexOf('--out');
const dist = outArg > 0 ? resolve(process.argv[outArg + 1]) : join(pkgDir, 'dist');
const engineSrc = join(pkgDir, '..', 'engine', 'src');
const require = createRequire(join(pkgDir, 'package.json'));

// ── the TypeScript lib files: lib.es2022.d.ts and everything it references (gates/compile.ts loadLibs) ──
const libDir = dirname(require.resolve('typescript/lib/lib.es2022.d.ts'));
const libs = {};
const pending = ['lib.es2022.d.ts'];
while (pending.length > 0) {
  const file = pending.shift();
  if (file in libs) continue;
  const text = readFileSync(join(libDir, file), 'utf8');
  libs[file] = text;
  for (const m of text.matchAll(/^\/\/\/\s*<reference\s+lib="([^"]+)"/gm)) pending.push(`lib.${m[1].toLowerCase()}.d.ts`);
}
const sortedLibs = Object.fromEntries(Object.keys(libs).sort().map((k) => [k, libs[k]]));

const embeddedId = join(pkgDir, 'src', 'embedded.ts');
const embedLibs = {
  name: 'undefined-embed-libs',
  load(id) {
    if (id === embeddedId) return `export const EMBEDDED_LIBS = ${JSON.stringify(sortedLibs)};\n`;
    return null;
  },
};

const banner = [
  '// undefined-certify GitHub Action. Generated by packages/action/scripts/build.mjs; do not edit.',
  '// Certifies code from any source; never generates code. NOT a secure sandbox: see packages/action/README.md.',
  "import { fileURLToPath as __undefinedFileURLToPath } from 'node:url';",
  "import { dirname as __undefinedDirname } from 'node:path';",
  // typescript.js reads __filename/__dirname at load; an ES module has neither
  'const __filename = __undefinedFileURLToPath(import.meta.url);',
  'const __dirname = __undefinedDirname(__filename);',
].join('\n');

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });

const modules = new Set();
const recordModules = { name: 'undefined-record-modules', moduleParsed(info) { modules.add(info.id); } };

const action = await rolldown({
  input: join(pkgDir, 'src', 'index.ts'),
  platform: 'node',
  logLevel: 'warn',
  // only reached when no prebuilt harness exists, which never happens from dist/
  external: ['rolldown'],
  plugins: [embedLibs, recordModules],
});
await action.write({ file: join(dist, 'index.js'), format: 'esm', codeSplitting: false, minify: false, banner, sourcemap: false });
await action.close();

// ── the in-realm harness: the same bundle the engine makes on first use (node/harnessSource.ts bundleHarness) ──
const harness = await rolldown({
  input: join(engineSrc, 'sandbox', 'vmHarness.ts'),
  platform: 'neutral',
  logLevel: 'silent',
  resolve: { mainFields: ['module', 'main'] },
  plugins: [recordModules],
});
const { output } = await harness.generate({ format: 'iife', name: '__undefinedHarness', minify: false });
await harness.close();
const chunk = output.find((o) => o.type === 'chunk');
if (!chunk) throw new Error('no harness chunk');
writeFileSync(join(dist, 'harness.js'), chunk.code);

copyFileSync(join(engineSrc, 'node', 'worker.mjs'), join(dist, 'worker.mjs'));
writeFileSync(join(dist, 'package.json'), `${JSON.stringify({ type: 'module', private: true }, null, 2)}\n`);

// ── licenses of every bundled package ──
const pkgs = new Map();
for (const id of modules) {
  const m = /^(.*[\\/]node_modules[\\/])((?:@[^\\/]+[\\/])?[^\\/]+)/.exec(id);
  if (!m) continue;
  const dir = m[1] + m[2];
  if (pkgs.has(dir)) continue;
  const pj = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  const lic = readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.|$)/i.test(f));
  pkgs.set(dir, { name: pj.name, version: pj.version, license: pj.license ?? 'unknown', text: lic ? readFileSync(join(dir, lic), 'utf8').trim() : '(no license file in the package)' });
}
const lines = ['Third-party packages bundled into dist/index.js and dist/harness.js.', ''];
for (const p of [...pkgs.values()].sort((a, b) => (a.name < b.name ? -1 : 1))) {
  lines.push('='.repeat(80), `${p.name}@${p.version} (${p.license})`, '='.repeat(80), p.text, '');
}
writeFileSync(join(dist, 'THIRD-PARTY-LICENSES.txt'), lines.join('\n'));

const size = (f) => (readFileSync(join(dist, f)).length / 1e6).toFixed(2);
if (!existsSync(join(dist, 'index.js'))) throw new Error('build failed: no dist/index.js');
console.log(
  `dist/: index.js ${size('index.js')} MB (${Object.keys(sortedLibs).length} lib files embedded), harness.js ${size('harness.js')} MB, worker.mjs; ${pkgs.size} bundled packages: ${[...pkgs.values()].map((p) => p.name).sort().join(', ')}`,
);
